name: Deploy dns zone

on:
  push:
    branches:
      - main

jobs:
  dnscontrol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy DNS zone
        uses: koenrh/dnscontrol-action@v3
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
        with:
          args: push
