name: Preview DNS zone

on: pull_request

jobs:
  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preview DNS zone
        uses: koenrh/dnscontrol-action@v3
        id: dnscontrol_preview
        env:
          OVH_APP_KEY: ${{ secrets.OVH_APP_KEY }}
          OVH_APP_SECRET: ${{ secrets.OVH_APP_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview

      - name: Preview pull request comment
        uses: unsplash/comment-on-pr@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            ```
            ${{ steps.dnscontrol_preview.outputs.output }}
            ```
          check_for_duplicate_msg: true
